import Foundation
import UIKit

// Phase 3: Loads keyboard layouts from the JSON files generated by
// convert_keyboard_layouts.py.  The JSON files live in Layouts/ inside the
// keyboard extension bundle.
//
// Usage:
//   let layout = LayoutLoader.load("lime_phonetic") ?? .phonetic

final class LayoutLoader {

    // MARK: - JSON Codable types (mirrors the Python converter output)

    private struct JSONLayout: Decodable {
        let id: String
        let defaultWidthPercent: Double
        let rows: [JSONRow]
    }

    private struct JSONRow: Decodable {
        let isBottomRow: Bool
        let keys: [JSONKey]
    }

    private struct JSONKey: Decodable {
        let code: Int
        let codes: [Int]?             // Multi-tap codes array; nil in single-code layouts
        let label: String
        let sublabel: String
        let widthPercent: Double
        let icon: String
        let isModifier: Bool
        let isRepeatable: Bool
        let isSticky: Bool
        let popupKeyboard: String
        let popupCharacters: String?  // nil in old JSONs without this field
        let longPressCode: Int?       // optional: nil if not present in JSON (old layouts)
    }

    // MARK: - Cache

    private static var cache: [String: LimeKeyLayout] = [:]
    private static let lock = NSLock()

    /// Set by KeyboardViewController based on the **host app's** trait collection
    /// (`traitCollection.userInterfaceIdiom == .pad`). This is NOT the same as
    /// `UIDevice.current.userInterfaceIdiom` — an iPhone-only app running on iPad
    /// in scaled/compatibility mode has `UIDevice == .pad` but the host trait
    /// collection reports `.phone`, so we must use the iPhone layout there.
    /// Defaults to false; controller updates this before any `load(_:)` call and
    /// again on `traitCollectionDidChange` (also clearing the cache).
    static var hostIsPad: Bool = false
    static var iPadSizeClass: IPadSizeClass = .large

    // MARK: - Public API

    /// Evict all cached layouts — call once per keyboard session start (viewDidLoad) so that
    /// layout JSON changes in a new build are picked up even if the extension process is reused.
    static func clearCache() {
        lock.lock()
        cache.removeAll()
        lock.unlock()
    }

    /// Load a layout by ID (e.g. "lime_phonetic").
    /// Returns nil if the JSON file is not found or fails to parse.
    static func load(_ id: String) -> LimeKeyLayout? {
        for resourceId in resourceCandidates(for: id) {
            lock.lock()
            if let cached = cache[resourceId] {
                lock.unlock()
                return cached
            }
            lock.unlock()

            if let layout = parseFromBundle(id: resourceId) {
                lock.lock()
                cache[resourceId] = layout
                lock.unlock()
                return layout
            }
        }
        return nil
    }

    static func iPadVariantCandidates(for id: String) -> [String] {
        resourceCandidates(for: id).filter { $0.contains("_ipad") }
    }

    static func applyingCj4Semicolon(to layout: LimeKeyLayout) -> LimeKeyLayout {
        let iPadSemicolonCodes: Set<Int> = layout.id.contains("_ipad") ? [65306, 65307] : [65306]
        if layout.rows.contains(where: { $0.keys.contains { iPadSemicolonCodes.contains($0.code) } }) {
            let rows = layout.rows.map { row in
                KeyRow(keys: row.keys.map { key in
                    guard iPadSemicolonCodes.contains(key.code) else { return key }
                    return KeyDef(
                        code: 59,
                        label: "'",
                        sublabel: ";",
                        widthPercent: key.widthPercent,
                        icon: key.icon,
                        isRepeatable: key.isRepeatable,
                        isModifier: key.isModifier,
                        isSticky: key.isSticky,
                        longPressCode: 39,
                        popupKeyboard: key.popupKeyboard,
                        popupCharacters: key.popupCharacters
                    )
                }, isBottomRow: row.isBottomRow)
            }
            return LimeKeyLayout(id: layout.id, rows: rows)
        }

        guard !layout.id.contains("_ipad") else { return layout }
        var didAppend = false
        let rows = layout.rows.map { row -> KeyRow in
            guard !didAppend,
                  row.keys.last?.code == 108 || row.keys.last?.code == 76 else {
                return row
            }
            didAppend = true
            return KeyRow(keys: row.keys + [KeyDef(code: 59, label: "'", sublabel: ";", widthPercent: 10,
                                                   longPressCode: 39,
                                                   popupKeyboard: "popup_template",
                                                   popupCharacters: "'")],
                          isBottomRow: row.isBottomRow)
        }
        return didAppend ? LimeKeyLayout(id: layout.id, rows: rows) : layout
    }

    // MARK: - Private

    private static func resourceParts(for id: String) -> (base: String, shifted: Bool) {
        var value = id
        var shifted = false

        if value.hasSuffix("_shift") {
            shifted = true
            value = String(value.dropLast("_shift".count))
        }
        if value.hasSuffix("_ipad_narrow") {
            value = String(value.dropLast("_ipad_narrow".count))
        } else if value.hasSuffix("_ipad") {
            value = String(value.dropLast("_ipad".count))
        }
        if value.hasSuffix("_shift") {
            shifted = true
            value = String(value.dropLast("_shift".count))
        }

        return (value, shifted)
    }

    private static func resourceId(base: String, iPadSuffix: String?, shifted: Bool) -> String {
        var value = base
        if let iPadSuffix {
            value += iPadSuffix
        }
        if shifted {
            value += "_shift"
        }
        return value
    }

    private static func resourceCandidates(for id: String) -> [String] {
        let parts = resourceParts(for: id)
        guard hostIsPad else {
            return [resourceId(base: parts.base, iPadSuffix: nil, shifted: parts.shifted)]
        }

        switch iPadSizeClass {
        case .small, .medium:
            return [
                resourceId(base: parts.base, iPadSuffix: "_ipad_narrow", shifted: parts.shifted),
                resourceId(base: parts.base, iPadSuffix: "_ipad", shifted: parts.shifted),
                resourceId(base: parts.base, iPadSuffix: nil, shifted: parts.shifted),
            ]
        case .large:
            return [
                resourceId(base: parts.base, iPadSuffix: "_ipad", shifted: parts.shifted),
                resourceId(base: parts.base, iPadSuffix: nil, shifted: parts.shifted),
            ]
        }
    }

    /// Splits an Android-style label string on the literal two-character sequences
    /// `\n` and `\t` (backslash + letter) that Android XML uses as separators:
    /// - `\n` separates primary label from sublabel
    /// - `\t` separates the English letter from the initial-position bopomofo in
    ///   dual-mapped phonetic keyboards (ETEN26 / HSU). Android renders these as
    ///   letter + initial side-by-side in the primary area; iOS collapses them into
    ///   a space-separated primary label (e.g. `"q ㄗ"`) so they share the primary
    ///   render path. The sublabel remains the final-position bopomofo.
    /// If `label` contains no `\n`, returns (label, fallbackSublabel) unchanged.
    private static func splitLabel(_ label: String, fallbackSublabel: String) -> (String, String) {
        // JSON "1\\nㄅ" → Swift string where index 1 is '\' and index 2 is 'n'
        let sepN = "\\" + "n"
        let sepT = "\\" + "t"
        let primary: String
        let sub: String
        if let range = label.range(of: sepN) {
            primary = String(label[label.startIndex..<range.lowerBound]).trimmingCharacters(in: .whitespaces)
            sub     = String(label[range.upperBound...]).trimmingCharacters(in: .whitespaces)
        } else {
            primary = label
            sub = fallbackSublabel
        }
        // Collapse any `\t` separators inside the primary portion to a single space
        // so the letter + initial-remap render together in the primary label.
        let collapsed = primary.replacingOccurrences(of: sepT, with: " ")
                               .replacingOccurrences(of: "  ", with: " ")
                               .trimmingCharacters(in: .whitespaces)
        return (collapsed, sub)
    }

    /// Resolve Android @string/ resource references to their iOS display strings.
    private static func resolveAndroidStringRef(_ label: String) -> String {
        switch label {
        case "@string/label_symbol_key":   return "123"
        case "@string/label_go_key":       return "Go"
        case "@string/label_send_key":     return "Send"
        case "@string/label_next_key":     return "Next"
        case "@string/label_done_key":     return "Done"
        case "@string/label_search_key":   return "Search"
        default:                           return label
        }
    }

    /// Resolve an Android @xml/ popup keyboard reference.
    /// - For real popup keyboards (e.g. @xml/popup_punctuation): returns the bare ID when the
    ///   JSON exists and has rows; "" otherwise.
    /// - For @xml/popup_template: always returns "popup_template" — the caller is responsible
    ///   for checking popupCharacters to decide whether to show the popup indicator.
    private static func resolvePopup(_ ref: String) -> String {
        guard !ref.isEmpty else { return "" }
        let id = ref.hasPrefix("@xml/") ? String(ref.dropFirst(5)) : ref
        if id == "popup_template" { return "popup_template" }
        guard let url = Bundle.main.url(forResource: id, withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let json = try? JSONDecoder().decode(JSONLayout.self, from: data),
              !json.rows.isEmpty
        else { return "" }
        return id
    }

    private static func parseFromBundle(id: String) -> LimeKeyLayout? {
        // XcodeGen copies the Layouts/ folder contents flat into the bundle root.
        guard let url = Bundle.main.url(forResource: id, withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else { return nil }

        let decoder = JSONDecoder()
        guard let json = try? decoder.decode(JSONLayout.self, from: data) else { return nil }

        let rows = json.rows.map { jr -> KeyRow in
            let keys = jr.keys.map { jk in
                // Android XML uses literal \n (backslash-n) as the label/sublabel separator,
                // e.g. keyLabel="1\nㄅ". Python's ET parser treats it as two chars (\ + n),
                // so the JSON stores "1\\nㄅ" → decoded Swift string "1\nㄅ" (backslash + n).
                // Split here so KeyDef always has separate label and sublabel fields.
                let (lbl, sub) = splitLabel(jk.label, fallbackSublabel: jk.sublabel)
                // Resolve Android @string/ label references to their iOS display values.
                let resolvedLabel = resolveAndroidStringRef(lbl)
                let popupChars = jk.popupCharacters ?? ""
                // Resolve popup keyboard reference.
                // popup_template with empty popupCharacters → clear (no popup).
                var resolvedPopup = resolvePopup(jk.popupKeyboard)
                if resolvedPopup == "popup_template" && popupChars.isEmpty {
                    resolvedPopup = ""
                }
                let keyCodes = (jk.codes?.isEmpty == false) ? jk.codes! : [jk.code]
                return KeyDef(
                    code:             keyCodes[0],
                    codes:            keyCodes,
                    label:            resolvedLabel,
                    sublabel:         sub,
                    widthPercent:     CGFloat(jk.widthPercent),
                    icon:             jk.icon,
                    isRepeatable:     jk.isRepeatable,
                    isModifier:       jk.isModifier,
                    isSticky:         jk.isSticky,
                    longPressCode:    jk.longPressCode ?? 0,
                    popupKeyboard:    resolvedPopup,
                    popupCharacters:  popupChars
                )
            }
            return KeyRow(keys: keys, isBottomRow: jr.isBottomRow)
        }
        return LimeKeyLayout(id: id, rows: rows)
    }

    /// Pre-warm the cache for commonly used layouts in the background.
    static func prefetchCommonLayouts() {
        let ids = [
            "lime_phonetic", "lime_phonetic_shift",
            "lime_abc", "lime_abc_shift",
            "lime_number", "symbols1", "symbols2", "symbols3",
        ]
        DispatchQueue.global(qos: .background).async {
            for id in ids { _ = load(id) }
        }
    }
}
